/**
 * ===========================================
 * CONSTANTES DO SISTEMA DE CONQUISTAS
 * ===========================================
 * 
 * Define todas as conquistas disponíveis no jogo.
 * Para adicionar uma nova conquista, basta adicionar aqui!
 */

import { Achievement } from "@/types/achievements";

/** @deprecated Não mais usado - conquistas salvas no banco por usuário */
export const ACHIEVEMENTS_STORAGE_KEY = "playerAchievements";
/** @deprecated Não mais usado - estatísticas salvas no banco por usuário */
export const PLAYER_STATS_STORAGE_KEY = "playerStats";

/** Lista de todas as conquistas do jogo */
export const ACHIEVEMENTS: Achievement[] = [
  // ============ CONQUISTAS GERAIS ============
  {
    id: "first_game",
    name: "Primeiro Passo",
    description: "Complete seu primeiro jogo",
    icon: "🎮",
    category: "general",
    condition: { type: "games_played", value: 1 },
  },
  {
    id: "getting_started",
    name: "Esquentando",
    description: "Complete 5 jogos",
    icon: "🔥",
    category: "general",
    condition: { type: "games_played", value: 5 },
  },
  {
    id: "veteran",
    name: "Veterano",
    description: "Complete 10 jogos",
    icon: "⭐",
    category: "general",
    condition: { type: "games_played", value: 10 },
  },
  {
    id: "dedicated",
    name: "Dedicado",
    description: "Complete 25 jogos",
    icon: "💪",
    category: "general",
    condition: { type: "games_played", value: 25 },
  },
  {
    id: "master_gamer",
    name: "Mestre dos Games",
    description: "Complete 50 jogos",
    icon: "👑",
    category: "general",
    condition: { type: "games_played", value: 50 },
  },
  {
    id: "legend",
    name: "Lenda Viva",
    description: "Complete 100 jogos",
    icon: "🏆",
    category: "general",
    condition: { type: "games_played", value: 100 },
  },

  // ============ CONQUISTAS MEMÓRIA ============
  {
    id: "memory_beginner",
    name: "Boa Memória",
    description: "Complete o modo Fácil",
    icon: "🧠",
    category: "memory",
    condition: { type: "games_played", game: "memory", value: 1 },
  },
  {
    id: "memory_fan",
    name: "Fã da Memória",
    description: "Complete 5 jogos de memória",
    icon: "💜",
    category: "memory",
    condition: { type: "games_played", game: "memory", value: 5 },
  },
  {
    id: "memory_addict",
    name: "Viciado em Memória",
    description: "Complete 20 jogos de memória",
    icon: "🎯",
    category: "memory",
    condition: { type: "games_played", game: "memory", value: 20 },
  },
  {
    id: "memory_perfect_easy",
    name: "Perfeição Fácil",
    description: "Complete Fácil em 8 movimentos ou menos",
    icon: "💯",
    category: "memory",
    condition: { type: "moves", game: "memory", difficulty: "easy", value: 8 },
  },
  {
    id: "memory_good_easy",
    name: "Eficiente",
    description: "Complete Fácil em 10 movimentos ou menos",
    icon: "✨",
    category: "memory",
    condition: { type: "moves", game: "memory", difficulty: "easy", value: 10 },
  },
  {
    id: "memory_perfect_medium",
    name: "Perfeição Média",
    description: "Complete Médio em 12 movimentos ou menos",
    icon: "🎖️",
    category: "memory",
    condition: { type: "moves", game: "memory", difficulty: "medium", value: 12 },
  },
  {
    id: "memory_good_medium",
    name: "Mente Afiada",
    description: "Complete Médio em 16 movimentos ou menos",
    icon: "🧩",
    category: "memory",
    condition: { type: "moves", game: "memory", difficulty: "medium", value: 16 },
  },
  {
    id: "memory_perfect_hard",
    name: "Memória Fotográfica",
    description: "Complete Difícil em 18 movimentos ou menos",
    icon: "📸",
    category: "memory",
    condition: { type: "moves", game: "memory", difficulty: "hard", value: 18 },
  },
  {
    id: "memory_good_hard",
    name: "Desafiador",
    description: "Complete Difícil em 24 movimentos ou menos",
    icon: "🎪",
    category: "memory",
    condition: { type: "moves", game: "memory", difficulty: "hard", value: 24 },
  },
  {
    id: "memory_speed_demon",
    name: "Velocista",
    description: "Complete qualquer modo em 30 segundos ou menos",
    icon: "⚡",
    category: "memory",
    condition: { type: "time", game: "memory", value: 30 },
  },
  {
    id: "memory_lightning",
    name: "Relâmpago",
    description: "Complete qualquer modo em 20 segundos ou menos",
    icon: "🌩️",
    category: "memory",
    condition: { type: "time", game: "memory", value: 20 },
  },
  {
    id: "memory_flash",
    name: "Flash",
    description: "Complete qualquer modo em 15 segundos ou menos",
    icon: "💨",
    category: "memory",
    condition: { type: "time", game: "memory", value: 15 },
  },

  // ============ CONQUISTAS SNAKE ============
  {
    id: "snake_first",
    name: "Primeira Mordida",
    description: "Jogue Snake pela primeira vez",
    icon: "🐍",
    category: "snake",
    condition: { type: "games_played", game: "snake", value: 1 },
  },
  {
    id: "snake_fan",
    name: "Fã de Cobras",
    description: "Jogue Snake 5 vezes",
    icon: "💚",
    category: "snake",
    condition: { type: "games_played", game: "snake", value: 5 },
  },
  {
    id: "snake_addict",
    name: "Viciado em Snake",
    description: "Jogue Snake 20 vezes",
    icon: "🎮",
    category: "snake",
    condition: { type: "games_played", game: "snake", value: 20 },
  },
  {
    id: "snake_20",
    name: "Primeiro Lanche",
    description: "Alcance 20 pontos no Snake",
    icon: "🍎",
    category: "snake",
    condition: { type: "score", game: "snake", value: 20 },
  },
  {
    id: "snake_50",
    name: "Cobra Crescendo",
    description: "Alcance 50 pontos no Snake",
    icon: "🌱",
    category: "snake",
    condition: { type: "score", game: "snake", value: 50 },
  },
  {
    id: "snake_80",
    name: "Serpente Habilidosa",
    description: "Alcance 80 pontos no Snake",
    icon: "🐲",
    category: "snake",
    condition: { type: "score", game: "snake", value: 80 },
  },
  {
    id: "snake_100",
    name: "Serpente Mestre",
    description: "Alcance 100 pontos no Snake",
    icon: "🔥",
    category: "snake",
    condition: { type: "score", game: "snake", value: 100 },
  },
  {
    id: "snake_150",
    name: "Cobra Gigante",
    description: "Alcance 150 pontos no Snake",
    icon: "🦎",
    category: "snake",
    condition: { type: "score", game: "snake", value: 150 },
  },
  {
    id: "snake_200",
    name: "Rei das Cobras",
    description: "Alcance 200 pontos no Snake",
    icon: "👑",
    category: "snake",
    condition: { type: "score", game: "snake", value: 200 },
  },
  {
    id: "snake_250",
    name: "Anaconda",
    description: "Alcance 250 pontos no Snake",
    icon: "🌊",
    category: "snake",
    condition: { type: "score", game: "snake", value: 250 },
  },
  {
    id: "snake_300",
    name: "Lenda Serpente",
    description: "Alcance 300 pontos no Snake",
    icon: "🌟",
    category: "snake",
    condition: { type: "score", game: "snake", value: 300 },
  },
  {
    id: "snake_400",
    name: "Deus das Cobras",
    description: "Alcance 400 pontos no Snake",
    icon: "⚡",
    category: "snake",
    condition: { type: "score", game: "snake", value: 400 },
  },
  {
    id: "snake_500",
    name: "Impossível!",
    description: "Alcance 500 pontos no Snake",
    icon: "🏆",
    category: "snake",
    condition: { type: "score", game: "snake", value: 500 },
  },

  // ============ CONQUISTAS DINO ============
  {
    id: "dino_first",
    name: "Primeiro Salto",
    description: "Jogue Dino Runner pela primeira vez",
    icon: "🦖",
    category: "dino",
    condition: { type: "games_played", game: "dino", value: 1 },
  },
  {
    id: "dino_fan",
    name: "Fã de Dinossauros",
    description: "Jogue Dino Runner 5 vezes",
    icon: "🦕",
    category: "dino",
    condition: { type: "games_played", game: "dino", value: 5 },
  },
  {
    id: "dino_addict",
    name: "Viciado em Correr",
    description: "Jogue Dino Runner 20 vezes",
    icon: "🏃",
    category: "dino",
    condition: { type: "games_played", game: "dino", value: 20 },
  },
  {
    id: "dino_50",
    name: "Aquecendo",
    description: "Alcance 50 pontos no Dino Runner",
    icon: "🌵",
    category: "dino",
    condition: { type: "score", game: "dino", value: 50 },
  },
  {
    id: "dino_100",
    name: "Corredor Veloz",
    description: "Alcance 100 pontos no Dino Runner",
    icon: "💨",
    category: "dino",
    condition: { type: "score", game: "dino", value: 100 },
  },
  {
    id: "dino_200",
    name: "Dinossauro Ágil",
    description: "Alcance 200 pontos no Dino Runner",
    icon: "⚡",
    category: "dino",
    condition: { type: "score", game: "dino", value: 200 },
  },
  {
    id: "dino_300",
    name: "T-Rex Mestre",
    description: "Alcance 300 pontos no Dino Runner",
    icon: "🔥",
    category: "dino",
    condition: { type: "score", game: "dino", value: 300 },
  },
  {
    id: "dino_500",
    name: "Rei dos Dinossauros",
    description: "Alcance 500 pontos no Dino Runner",
    icon: "👑",
    category: "dino",
    condition: { type: "score", game: "dino", value: 500 },
  },
  {
    id: "dino_750",
    name: "Lenda Jurássica",
    description: "Alcance 750 pontos no Dino Runner",
    icon: "🌟",
    category: "dino",
    condition: { type: "score", game: "dino", value: 750 },
  },
  {
    id: "dino_1000",
    name: "Era Mesozóica",
    description: "Alcance 1000 pontos no Dino Runner",
    icon: "🏆",
    category: "dino",
    condition: { type: "score", game: "dino", value: 1000 },
  },

  // ============ CONQUISTAS TETRIS ============
  {
    id: "tetris_first",
    name: "Empilhador",
    description: "Jogue Tetris pela primeira vez",
    icon: "🧱",
    category: "tetris",
    condition: { type: "games_played", game: "tetris", value: 1 },
  },
  {
    id: "tetris_fan",
    name: "Fã de Blocos",
    description: "Jogue Tetris 5 vezes",
    icon: "💙",
    category: "tetris",
    condition: { type: "games_played", game: "tetris", value: 5 },
  },
  {
    id: "tetris_addict",
    name: "Viciado em Tetris",
    description: "Jogue Tetris 20 vezes",
    icon: "🎮",
    category: "tetris",
    condition: { type: "games_played", game: "tetris", value: 20 },
  },
  {
    id: "tetris_1000",
    name: "Primeiros Pontos",
    description: "Alcance 1000 pontos no Tetris",
    icon: "⭐",
    category: "tetris",
    condition: { type: "score", game: "tetris", value: 1000 },
  },
  {
    id: "tetris_5000",
    name: "Empilhador Habilidoso",
    description: "Alcance 5000 pontos no Tetris",
    icon: "🌟",
    category: "tetris",
    condition: { type: "score", game: "tetris", value: 5000 },
  },
  {
    id: "tetris_10000",
    name: "Mestre dos Blocos",
    description: "Alcance 10000 pontos no Tetris",
    icon: "🔥",
    category: "tetris",
    condition: { type: "score", game: "tetris", value: 10000 },
  },
  {
    id: "tetris_25000",
    name: "Lenda do Tetris",
    description: "Alcance 25000 pontos no Tetris",
    icon: "👑",
    category: "tetris",
    condition: { type: "score", game: "tetris", value: 25000 },
  },
  {
    id: "tetris_50000",
    name: "Deus do Tetris",
    description: "Alcance 50000 pontos no Tetris",
    icon: "🏆",
    category: "tetris",
    condition: { type: "score", game: "tetris", value: 50000 },
  },
  {
    id: "tetris_10_lines",
    name: "Primeira Limpa",
    description: "Limpe 10 linhas em uma partida",
    icon: "📏",
    category: "tetris",
    condition: { type: "lines", game: "tetris", value: 10 },
  },
  {
    id: "tetris_50_lines",
    name: "Limpador",
    description: "Limpe 50 linhas em uma partida",
    icon: "🧹",
    category: "tetris",
    condition: { type: "lines", game: "tetris", value: 50 },
  },
  {
    id: "tetris_100_lines",
    name: "Limpeza Total",
    description: "Limpe 100 linhas em uma partida",
    icon: "✨",
    category: "tetris",
    condition: { type: "lines", game: "tetris", value: 100 },
  },
  {
    id: "tetris_level_5",
    name: "Nível 5",
    description: "Alcance o nível 5 no Tetris",
    icon: "📈",
    category: "tetris",
    condition: { type: "level", game: "tetris", value: 5 },
  },
  {
    id: "tetris_level_10",
    name: "Nível 10",
    description: "Alcance o nível 10 no Tetris",
    icon: "🚀",
    category: "tetris",
    condition: { type: "level", game: "tetris", value: 10 },
  },
  {
    id: "tetris_level_15",
    name: "Velocidade Máxima",
    description: "Alcance o nível 15 no Tetris",
    icon: "⚡",
    category: "tetris",
    condition: { type: "level", game: "tetris", value: 15 },
  },

  // ============ CONQUISTAS TOP 3 (ESPECIAIS) ============
  {
    id: "top3_snake",
    name: "Elite Snake",
    description: "Fique no Top 3 do ranking de Snake",
    icon: "👑",
    category: "general",
    condition: { type: "custom", value: 0 },
  },
  {
    id: "top3_dino",
    name: "Elite Dino",
    description: "Fique no Top 3 do ranking de Dino Runner",
    icon: "👑",
    category: "general",
    condition: { type: "custom", value: 0 },
  },
  {
    id: "top3_tetris",
    name: "Elite Tetris",
    description: "Fique no Top 3 do ranking de Tetris",
    icon: "👑",
    category: "general",
    condition: { type: "custom", value: 0 },
  },
  {
    id: "top3_memory",
    name: "Elite Memória",
    description: "Fique no Top 3 do ranking de Memória",
    icon: "👑",
    category: "general",
    condition: { type: "custom", value: 0 },
  },
  {
    id: "champion",
    name: "Campeão",
    description: "Fique em 1º lugar em qualquer ranking",
    icon: "🏆",
    category: "general",
    condition: { type: "custom", value: 0 },
  },
];

/** Conquistas agrupadas por categoria */
export const ACHIEVEMENTS_BY_CATEGORY = {
  general: ACHIEVEMENTS.filter(a => a.category === "general"),
  memory: ACHIEVEMENTS.filter(a => a.category === "memory"),
  snake: ACHIEVEMENTS.filter(a => a.category === "snake"),
  dino: ACHIEVEMENTS.filter(a => a.category === "dino"),
  tetris: ACHIEVEMENTS.filter(a => a.category === "tetris"),
};
